# Setup
title: hongwei Zhang
description: 前端小白
url: https://github.com/hwzhang9
avatar: /avatar/1.jpeg
paginate: 5
permalink: pretty
cover_image: /bg/1.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: 1111
  card: summary
logo: logo.png
social:
  name: hongwei Zhang
  links:
    - https://twitter.com
    - https://github.com/hwzhang9
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: hongwei Zhang
  url: https://github.com/hwzhang9
  email: 2579685223@qq.com

theme: jekyll-theme-cayman